apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
        env: dev
    spec:
      containers:
      - name: account
        image: adilmahmood/microservices-demo:account
        ports:
        - containerPort: 2222
