apiVersion: v1
kind: Service
metadata:
 name: account-service
spec:
 type: NodePort
 selector:
   app: account
   env: dev
 ports:
 - nodePort: 32410
   protocol: TCP
   port: 2222
   targetPort: 2222